name: monedata
description: Monedata Flutter plugin
version: 1.4.5
homepage: https://monedata.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.monedata.flutter
        pluginClass: MonedataFlutterPlugin
